CREATE TABLE post(
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(250) NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);

CREATE TABLE comment(
	id INT AUTO_INCREMENT PRIMARY KEY,
	comment VARCHAR(250) NOT NULL,
	username VARCHAR(100) NOT NULL,
	post_id INT NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	CONSTRAINT FOREIGN KEY (post_id) REFERENCES post(id)
);
